### ISSUE TITLE
Useless css in src/index.css

### ISSUE THREAD

**Issue by flacombe** [openinframap/openinframap#181]
Hello

I suspect lines 71 to 99 in src/index.css are useless and could be removed.

```css
.infobox {
  display: block;
  position: absolute;
  bottom: 40px;
  min-width: 60px;
  max-width: 300px;
  left: 5%;
  background-color: white;
  padding: 5px;
  border: 1px solid #999;
  border-radius: 4px;
}

.infobox-header {
  font-weight: bold;
  padding-bottom: 5px;
  border-bottom: 1px solid #bbb;
  margin-bottom: 4px;
}

.infobox-header a {
  cursor: pointer;
  float: right;
  margin-top: -3px;
}

.infobox-content {
  clear: both;
}
```

These styles are superseded by `maplibre-popup*` classes.

Regards
